[book]
title = "Documentación de Ichika"
description = "Una biblioteca de macros procedurales de Rust para construir canalizaciones basadas en grupos de hilos"
authors = ["celestia-island"]
language = "es"
src = "."

[build]
build-dir = "../../target/docs/es"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/celestia-island/ichika"
edit-url-template = "https://github.com/celestia-island/ichika/edit/next/docs/es/{path}"
additional-js = ["../theme/lang-switcher.js"]
additional-css = ["../theme/lang-switcher.css"]
