[site]
title = "Ichika"
description = "A helper library for automatically constructing a thread pool that communicates via message pipes."

[languages]
default = "en"
order = ["en", "zhs", "zht", "ja", "ko", "fr", "es", "ru", "ar"]
